
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTAND ASC BY COMMA COPY DELETE DESC DRYRUN FROM ID LIKE LIMIT LPAREN MOVE NOT NUMBER OPERATOR OR ORDER RPAREN SELECT SEMICOLON SIZE_UNIT STAR STRING TO WHEREprogram : statement SEMICOLON\n| program statement SEMICOLONstatement : dryrun_opt querydryrun_opt : DRYRUN\n| emptyquery : select_query\n| delete_query\n| move_query\n| copy_queryselect_query : SELECT column_list FROM STRING where_clause order_clause limit_clausedelete_query : DELETE FROM STRING where_clause limit_clausemove_query : MOVE FROM STRING TO STRING where_clause limit_clausecopy_query : COPY FROM STRING TO STRING where_clause limit_clausecolumn_list : STARcolumn_list : id_listid_list : ID\n| ID COMMA id_listwhere_clause : WHERE condition\n| emptycondition : condition AND condition\n| condition OR conditioncondition : NOT conditioncondition : LPAREN condition RPARENcondition : ID OPERATOR valuecondition : ID LIKE STRINGvalue : STRING\n| NUMBERvalue : NUMBER SIZE_UNITorder_clause : ORDER BY ID\n| ORDER BY ID ASC\n| ORDER BY ID DESC\n| emptylimit_clause : LIMIT NUMBER\n| emptyempty :'
    
_lr_action_items = {'DRYRUN':([0,1,7,17,],[4,4,-1,-2,]),'SELECT':([0,1,3,4,5,7,17,],[-35,-35,13,-4,-5,-1,-2,]),'DELETE':([0,1,3,4,5,7,17,],[-35,-35,14,-4,-5,-1,-2,]),'MOVE':([0,1,3,4,5,7,17,],[-35,-35,15,-4,-5,-1,-2,]),'COPY':([0,1,3,4,5,7,17,],[-35,-35,16,-4,-5,-1,-2,]),'$end':([1,7,17,],[0,-1,-2,]),'SEMICOLON':([2,6,8,9,10,11,12,27,30,32,34,37,38,40,41,45,46,47,49,50,53,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,],[7,17,-3,-6,-7,-8,-9,-35,-35,-35,-19,-35,-11,-34,-18,-35,-35,-35,-32,-33,-22,-35,-35,-10,-20,-21,-23,-24,-26,-27,-25,-12,-13,-29,-28,-30,-31,]),'STAR':([13,],[19,]),'ID':([13,26,33,42,43,51,52,60,],[21,21,44,44,44,44,44,70,]),'FROM':([14,15,16,18,19,20,21,31,],[22,23,24,25,-14,-15,-16,-17,]),'COMMA':([21,],[26,]),'STRING':([22,23,24,25,35,36,55,56,],[27,28,29,30,45,46,65,67,]),'WHERE':([27,30,45,46,],[33,33,33,33,]),'LIMIT':([27,30,32,34,37,41,45,46,47,49,53,57,58,61,62,63,64,65,66,67,70,71,72,73,],[-35,-35,39,-19,-35,-18,-35,-35,39,-32,-22,39,39,-20,-21,-23,-24,-26,-27,-25,-29,-28,-30,-31,]),'TO':([28,29,],[35,36,]),'ORDER':([30,34,37,41,53,61,62,63,64,65,66,67,71,],[-35,-19,48,-18,-22,-20,-21,-23,-24,-26,-27,-25,-28,]),'NOT':([33,42,43,51,52,],[42,42,42,42,42,]),'LPAREN':([33,42,43,51,52,],[43,43,43,43,43,]),'NUMBER':([39,55,],[50,66,]),'AND':([41,53,54,61,62,63,64,65,66,67,71,],[51,-22,51,-20,51,-23,-24,-26,-27,-25,-28,]),'OR':([41,53,54,61,62,63,64,65,66,67,71,],[52,-22,52,-20,-21,-23,-24,-26,-27,-25,-28,]),'OPERATOR':([44,],[55,]),'LIKE':([44,],[56,]),'BY':([48,],[60,]),'RPAREN':([53,54,61,62,63,64,65,66,67,71,],[-22,63,-20,-21,-23,-24,-26,-27,-25,-28,]),'SIZE_UNIT':([66,],[71,]),'ASC':([70,],[72,]),'DESC':([70,],[73,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,6,]),'dryrun_opt':([0,1,],[3,3,]),'empty':([0,1,27,30,32,37,45,46,47,57,58,],[5,5,34,34,40,49,34,34,40,40,40,]),'query':([3,],[8,]),'select_query':([3,],[9,]),'delete_query':([3,],[10,]),'move_query':([3,],[11,]),'copy_query':([3,],[12,]),'column_list':([13,],[18,]),'id_list':([13,26,],[20,31,]),'where_clause':([27,30,45,46,],[32,37,57,58,]),'limit_clause':([32,47,57,58,],[38,59,68,69,]),'condition':([33,42,43,51,52,],[41,53,54,61,62,]),'order_clause':([37,],[47,]),'value':([55,],[64,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement SEMICOLON','program',2,'p_program','dirsql_parser.py',12),
  ('program -> program statement SEMICOLON','program',3,'p_program','dirsql_parser.py',13),
  ('statement -> dryrun_opt query','statement',2,'p_statement','dirsql_parser.py',22),
  ('dryrun_opt -> DRYRUN','dryrun_opt',1,'p_dryrun_opt','dirsql_parser.py',26),
  ('dryrun_opt -> empty','dryrun_opt',1,'p_dryrun_opt','dirsql_parser.py',27),
  ('query -> select_query','query',1,'p_query','dirsql_parser.py',31),
  ('query -> delete_query','query',1,'p_query','dirsql_parser.py',32),
  ('query -> move_query','query',1,'p_query','dirsql_parser.py',33),
  ('query -> copy_query','query',1,'p_query','dirsql_parser.py',34),
  ('select_query -> SELECT column_list FROM STRING where_clause order_clause limit_clause','select_query',7,'p_select_query','dirsql_parser.py',38),
  ('delete_query -> DELETE FROM STRING where_clause limit_clause','delete_query',5,'p_delete_query','dirsql_parser.py',53),
  ('move_query -> MOVE FROM STRING TO STRING where_clause limit_clause','move_query',7,'p_move_query','dirsql_parser.py',63),
  ('copy_query -> COPY FROM STRING TO STRING where_clause limit_clause','copy_query',7,'p_copy_query','dirsql_parser.py',74),
  ('column_list -> STAR','column_list',1,'p_column_list_star','dirsql_parser.py',86),
  ('column_list -> id_list','column_list',1,'p_column_list_id','dirsql_parser.py',90),
  ('id_list -> ID','id_list',1,'p_id_list','dirsql_parser.py',94),
  ('id_list -> ID COMMA id_list','id_list',3,'p_id_list','dirsql_parser.py',95),
  ('where_clause -> WHERE condition','where_clause',2,'p_where_clause','dirsql_parser.py',103),
  ('where_clause -> empty','where_clause',1,'p_where_clause','dirsql_parser.py',104),
  ('condition -> condition AND condition','condition',3,'p_condition_binop','dirsql_parser.py',112),
  ('condition -> condition OR condition','condition',3,'p_condition_binop','dirsql_parser.py',113),
  ('condition -> NOT condition','condition',2,'p_condition_not','dirsql_parser.py',117),
  ('condition -> LPAREN condition RPAREN','condition',3,'p_condition_group','dirsql_parser.py',121),
  ('condition -> ID OPERATOR value','condition',3,'p_condition_rel','dirsql_parser.py',125),
  ('condition -> ID LIKE STRING','condition',3,'p_condition_like','dirsql_parser.py',129),
  ('value -> STRING','value',1,'p_value','dirsql_parser.py',134),
  ('value -> NUMBER','value',1,'p_value','dirsql_parser.py',135),
  ('value -> NUMBER SIZE_UNIT','value',2,'p_value_size','dirsql_parser.py',139),
  ('order_clause -> ORDER BY ID','order_clause',3,'p_order_clause','dirsql_parser.py',144),
  ('order_clause -> ORDER BY ID ASC','order_clause',4,'p_order_clause','dirsql_parser.py',145),
  ('order_clause -> ORDER BY ID DESC','order_clause',4,'p_order_clause','dirsql_parser.py',146),
  ('order_clause -> empty','order_clause',1,'p_order_clause','dirsql_parser.py',147),
  ('limit_clause -> LIMIT NUMBER','limit_clause',2,'p_limit_clause','dirsql_parser.py',155),
  ('limit_clause -> empty','limit_clause',1,'p_limit_clause','dirsql_parser.py',156),
  ('empty -> <empty>','empty',0,'p_empty','dirsql_parser.py',161),
]
