
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDAND COMMA FROM ID NUMBER OPERATOR OR SELECT SEMICOLON STAR STRING WHEREprogram : query SEMICOLONquery : SELECT column_list FROM STRING where_clausecolumn_list : STARcolumn_list : IDcolumn_list : column_list COMMA IDwhere_clause :where_clause : WHERE conditioncondition : condition AND condition\n                 | condition OR conditioncondition : ID OPERATOR valuevalue : STRINGvalue : NUMBER'
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,4,],[0,-1,]),'SEMICOLON':([2,10,12,14,19,20,21,22,23,],[4,-6,-2,-7,-8,-9,-10,-11,-12,]),'STAR':([3,],[6,]),'ID':([3,9,13,16,17,],[7,11,15,15,15,]),'FROM':([5,6,7,11,],[8,-3,-4,-5,]),'COMMA':([5,6,7,11,],[9,-3,-4,-5,]),'STRING':([8,18,],[10,22,]),'WHERE':([10,],[13,]),'AND':([14,19,20,21,22,23,],[16,-8,16,-10,-11,-12,]),'OR':([14,19,20,21,22,23,],[17,-8,-9,-10,-11,-12,]),'OPERATOR':([15,],[18,]),'NUMBER':([18,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'query':([0,],[2,]),'column_list':([3,],[5,]),'where_clause':([10,],[12,]),'condition':([13,16,17,],[14,19,20,]),'value':([18,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> query SEMICOLON','program',2,'p_program','parser.py',11),
  ('query -> SELECT column_list FROM STRING where_clause','query',5,'p_query','parser.py',18),
  ('column_list -> STAR','column_list',1,'p_column_list_star','parser.py',29),
  ('column_list -> ID','column_list',1,'p_column_list_single','parser.py',33),
  ('column_list -> column_list COMMA ID','column_list',3,'p_column_list_multiple','parser.py',37),
  ('where_clause -> <empty>','where_clause',0,'p_where_clause_empty','parser.py',43),
  ('where_clause -> WHERE condition','where_clause',2,'p_where_clause','parser.py',47),
  ('condition -> condition AND condition','condition',3,'p_condition_logic','parser.py',53),
  ('condition -> condition OR condition','condition',3,'p_condition_logic','parser.py',54),
  ('condition -> ID OPERATOR value','condition',3,'p_condition_relation','parser.py',63),
  ('value -> STRING','value',1,'p_value_string','parser.py',74),
  ('value -> NUMBER','value',1,'p_value_number','parser.py',78),
]
